Backport for Cart page rendering
spryker/product-review pull request #5
Opened 2021-08-12 07:21 UTC by dimitriyTsemma

- Developer(s): @geega

- Ticket: https://spryker.atlassian.net/browse/TE-9003

- Release Group: https://release.spryker.com/release-groups/view/3734

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   ProductReview         | minor                 |                       |

-----------------------------------------

#### Module ProductReview

##### Change log

Improvements

- Introduced `ProductReviewClient::expandProductViewBatchWithProductReviewData()` to batch expands product view data with product review summary data (average rating).

2021-08-17 13:45 UTC, gechetspr requested changes
Please change code after you change core repo.

Also changelogs should include all public api changes. I don't see any transfers in the changelogs

2021-08-17 13:46 UTC, gechetspr commented
Also I'm quite sure that you need to update composer.json file too

2021-09-03 09:46 UTC, demkos approved these changes

2021-09-03 11:43 UTC, gechetspr approved these changes

2021-09-03 14:51 UTC, closed without merging